package org.sopeco.engine.status;

/**
 * 
 * @author Marius Oehler
 * 
 */
public enum EventType {
	ACQUIRE_MEC, 
	ACQUIRE_MEC_FAILED, 
	EXECUTION_FAILED, 
	EXECUTE_EXPERIMENTRUN, 
	EXPERIMENT_EXECUTION,
	FINALIZE_EXPERIMENTSERIES, 
	INIT_MEC, 
	MEASUREMENT_FINISHED, 
	PREPARE_EXPERIMENTSERIES, 
	RELEASE_MEC,
	CONNECT_TO_MEC,
	ERROR
}
