//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.15 at 01:57:20 PM MESZ 
//


package org.sopeco.engine.model.xmlentities;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	
	
    public final static QName SCENARIO_QNAME = new QName("http://www.sopeco.org/SoPeCoScenarioDefinitionSchema", "scenario");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XExperimentSeriesDefinition.ExperimentSeriesPreparation }
     * 
     */
    public XExperimentSeriesDefinition.ExperimentSeriesPreparation createExperimentSeriesDefinitionExperimentSeriesPreparation() {
        return new XExperimentSeriesDefinition.ExperimentSeriesPreparation();
    }

    /**
     * Create an instance of {@link XScenarioDefinition }
     * 
     */
    public XScenarioDefinition createScenarioDefinition() {
        return new XScenarioDefinition();
    }

    /**
     * Create an instance of {@link XExtensibleElement }
     * 
     */
    public XExtensibleElement createExtensibleElement() {
        return new XExtensibleElement();
    }

    /**
     * Create an instance of {@link XConstantValueAssignment }
     * 
     */
    public XConstantValueAssignment createConstantValueAssignment() {
        return new XConstantValueAssignment();
    }

    /**
     * Create an instance of {@link XConfigurationNode }
     * 
     */
    public XConfigurationNode createConfigurationNode() {
        return new XConfigurationNode();
    }

    /**
     * Create an instance of {@link XExplorationStrategy }
     * 
     */
    public XExplorationStrategy createExplorationStrategy() {
        return new XExplorationStrategy();
    }

    /**
     * Create an instance of {@link XDynamicValueAssignment }
     * 
     */
    public XDynamicValueAssignment createDynamicValueAssignment() {
        return new XDynamicValueAssignment();
    }

    /**
     * Create an instance of {@link XAnalysisConfiguration }
     * 
     */
    public XAnalysisConfiguration createAnalysisConfiguration() {
        return new XAnalysisConfiguration();
    }

    /**
     * Create an instance of {@link XMeasurementSpecification }
     * 
     */
    public XMeasurementSpecification createMeasurementSpecification() {
        return new XMeasurementSpecification();
    }

    /**
     * Create an instance of {@link XExperimentSeriesDefinition.ExperimentSeriesExecution }
     * 
     */
    public XExperimentSeriesDefinition.ExperimentSeriesExecution createExperimentSeriesDefinitionExperimentSeriesExecution() {
        return new XExperimentSeriesDefinition.ExperimentSeriesExecution();
    }

    /**
     * Create an instance of {@link XExperimentSeriesDefinition }
     * 
     */
    public XExperimentSeriesDefinition createExperimentSeriesDefinition() {
        return new XExperimentSeriesDefinition();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XScenarioDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sopeco.org/SoPeCoScenarioDefinitionSchema", name = "scenario")
    public JAXBElement<XScenarioDefinition> createScenario(XScenarioDefinition value) {
        return new JAXBElement<XScenarioDefinition>(SCENARIO_QNAME, XScenarioDefinition.class, null, value);
    }

}
