//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.15 at 01:57:20 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sopeco.org/SoPeCoScenarioDefinitionSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sopeco.engine.model.xmlentities;

