//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.15 at 01:57:20 PM MESZ 
//


package org.sopeco.engine.model.xmlentities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExplorationStrategy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExplorationStrategy">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}ExtensibleElement">
 *       &lt;sequence>
 *         &lt;element name="analysisConfig" type="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}AnalysisConfiguration" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExplorationStrategy", propOrder = {
    "analysisConfig"
})
public class XExplorationStrategy
    extends XExtensibleElement
{

    protected List<XAnalysisConfiguration> analysisConfig;

    /**
     * Gets the value of the analysisConfig property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the analysisConfig property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnalysisConfig().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XAnalysisConfiguration }
     * 
     * 
     */
    public List<XAnalysisConfiguration> getAnalysisConfig() {
        if (analysisConfig == null) {
            analysisConfig = new ArrayList<XAnalysisConfiguration>();
        }
        return this.analysisConfig;
    }

}
