/**
 * Copyright (c) 2013 SAP
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the SAP nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL SAP BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.15 at 01:57:20 PM MESZ 
//



package org.sopeco.engine.model.xmlentities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExperimentSeriesDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExperimentSeriesDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="explorationStrategy" type="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}ExplorationStrategy"/>
 *         &lt;element name="terminationCondition" type="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}ExtensibleElement"/>
 *         &lt;element name="experimentSeriesPreparation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="constantAssignment" type="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}ConstantValueAssignment" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="experimentSeriesExecution">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="constantAssignment" type="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}ConstantValueAssignment" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="dynamicAssignment" type="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}DynamicValueAssignment" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExperimentSeriesDefinition", propOrder = {

})
public class XExperimentSeriesDefinition {

    @XmlElement(required = true)
    protected XExplorationStrategy explorationStrategy;
    protected XExperimentTerminationCondition terminationConditions;
    protected XExperimentSeriesDefinition.ExperimentSeriesPreparation experimentSeriesPreparation;
    @XmlElement(required = true)
    protected XExperimentSeriesDefinition.ExperimentSeriesExecution experimentSeriesExecution;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the explorationStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link XExplorationStrategy }
     *     
     */
    public XExplorationStrategy getExplorationStrategy() {
        return explorationStrategy;
    }

    /**
     * Sets the value of the explorationStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link XExplorationStrategy }
     *     
     */
    public void setExplorationStrategy(XExplorationStrategy value) {
        this.explorationStrategy = value;
    }



    /**
     * Gets the value of the experimentSeriesPreparation property.
     * 
     * @return
     *     possible object is
     *     {@link XExperimentSeriesDefinition.ExperimentSeriesPreparation }
     *     
     */
    public XExperimentSeriesDefinition.ExperimentSeriesPreparation getExperimentSeriesPreparation() {
        return experimentSeriesPreparation;
    }

    /**
     * Sets the value of the experimentSeriesPreparation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XExperimentSeriesDefinition.ExperimentSeriesPreparation }
     *     
     */
    public void setExperimentSeriesPreparation(XExperimentSeriesDefinition.ExperimentSeriesPreparation value) {
        this.experimentSeriesPreparation = value;
    }

    /**
     * Gets the value of the experimentSeriesExecution property.
     * 
     * @return
     *     possible object is
     *     {@link XExperimentSeriesDefinition.ExperimentSeriesExecution }
     *     
     */
    public XExperimentSeriesDefinition.ExperimentSeriesExecution getExperimentSeriesExecution() {
        return experimentSeriesExecution;
    }

    /**
     * Sets the value of the experimentSeriesExecution property.
     * 
     * @param value
     *     allowed object is
     *     {@link XExperimentSeriesDefinition.ExperimentSeriesExecution }
     *     
     */
    public void setExperimentSeriesExecution(XExperimentSeriesDefinition.ExperimentSeriesExecution value) {
        this.experimentSeriesExecution = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    public XExperimentTerminationCondition getTerminationCondition() {
		return terminationConditions;
	}

	public void setTerminationCondition(XExperimentTerminationCondition terminationCondition) {
		this.terminationConditions = terminationCondition;
	}


	/**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="constantAssignment" type="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}ConstantValueAssignment" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="dynamicAssignment" type="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}DynamicValueAssignment" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "constantAssignment",
        "dynamicAssignment"
    })
    public static class ExperimentSeriesExecution {

        protected List<XConstantValueAssignment> constantAssignment;
        protected List<XDynamicValueAssignment> dynamicAssignment;

        /**
         * Gets the value of the constantAssignment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the constantAssignment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConstantAssignment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XConstantValueAssignment }
         * 
         * 
         */
        public List<XConstantValueAssignment> getConstantAssignment() {
            if (constantAssignment == null) {
                constantAssignment = new ArrayList<XConstantValueAssignment>();
            }
            return this.constantAssignment;
        }

        /**
         * Gets the value of the dynamicAssignment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dynamicAssignment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDynamicAssignment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XDynamicValueAssignment }
         * 
         * 
         */
        public List<XDynamicValueAssignment> getDynamicAssignment() {
            if (dynamicAssignment == null) {
                dynamicAssignment = new ArrayList<XDynamicValueAssignment>();
            }
            return this.dynamicAssignment;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="constantAssignment" type="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}ConstantValueAssignment" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "constantAssignment"
    })
    public static class ExperimentSeriesPreparation {

        protected List<XConstantValueAssignment> constantAssignment;

        /**
         * Gets the value of the constantAssignment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the constantAssignment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConstantAssignment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XConstantValueAssignment }
         * 
         * 
         */
        public List<XConstantValueAssignment> getConstantAssignment() {
            if (constantAssignment == null) {
                constantAssignment = new ArrayList<XConstantValueAssignment>();
            }
            return this.constantAssignment;
        }

    }

}
