//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.15 at 01:57:20 PM MESZ 
//


package org.sopeco.engine.model.xmlentities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasurementSpecification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasurementSpecification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="experimentSeries" type="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}ExperimentSeriesDefinition" maxOccurs="unbounded"/>
 *         &lt;element name="initializationAssignments" type="{http://www.sopeco.org/SoPeCoScenarioDefinitionSchema}ConstantValueAssignment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasurementSpecification", propOrder = {
    "experimentSeries",
    "initializationAssignments"
})
public class XMeasurementSpecification {

    @XmlElement(required = true)
    protected List<XExperimentSeriesDefinition> experimentSeries;
    protected List<XConstantValueAssignment> initializationAssignments;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the experimentSeries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the experimentSeries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExperimentSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XExperimentSeriesDefinition }
     * 
     * 
     */
    public List<XExperimentSeriesDefinition> getExperimentSeries() {
        if (experimentSeries == null) {
            experimentSeries = new ArrayList<XExperimentSeriesDefinition>();
        }
        return this.experimentSeries;
    }

    /**
     * Gets the value of the initializationAssignments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the initializationAssignments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInitializationAssignments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XConstantValueAssignment }
     * 
     * 
     */
    public List<XConstantValueAssignment> getInitializationAssignments() {
        if (initializationAssignments == null) {
            initializationAssignments = new ArrayList<XConstantValueAssignment>();
        }
        return this.initializationAssignments;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
