/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.sopeco.model.configuration.measurements.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.sopeco.model.configuration.measurements.util.MeasurementsAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class MeasurementsItemProviderAdapterFactory extends MeasurementsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MeasurementsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.sopeco.model.configuration.measurements.MeasurementSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeasurementSpecificationItemProvider measurementSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.sopeco.model.configuration.measurements.MeasurementSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeasurementSpecificationAdapter() {
		if (measurementSpecificationItemProvider == null) {
			measurementSpecificationItemProvider = new MeasurementSpecificationItemProvider(this);
		}

		return measurementSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.sopeco.model.configuration.measurements.ExperimentSeriesDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExperimentSeriesDefinitionItemProvider experimentSeriesDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.sopeco.model.configuration.measurements.ExperimentSeriesDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExperimentSeriesDefinitionAdapter() {
		if (experimentSeriesDefinitionItemProvider == null) {
			experimentSeriesDefinitionItemProvider = new ExperimentSeriesDefinitionItemProvider(this);
		}

		return experimentSeriesDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.sopeco.model.configuration.measurements.ExplorationStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExplorationStrategyItemProvider explorationStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link org.sopeco.model.configuration.measurements.ExplorationStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExplorationStrategyAdapter() {
		if (explorationStrategyItemProvider == null) {
			explorationStrategyItemProvider = new ExplorationStrategyItemProvider(this);
		}

		return explorationStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurationNodeItemProvider configurationNodeItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigurationNodeAdapter() {
		if (configurationNodeItemProvider == null) {
			configurationNodeItemProvider = new ConfigurationNodeItemProvider(this);
		}

		return configurationNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.sopeco.model.configuration.measurements.NumberOfRepetitions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumberOfRepetitionsItemProvider numberOfRepetitionsItemProvider;

	/**
	 * This creates an adapter for a {@link org.sopeco.model.configuration.measurements.NumberOfRepetitions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumberOfRepetitionsAdapter() {
		if (numberOfRepetitionsItemProvider == null) {
			numberOfRepetitionsItemProvider = new NumberOfRepetitionsItemProvider(this);
		}

		return numberOfRepetitionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.sopeco.model.configuration.measurements.TimeOut} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimeOutItemProvider timeOutItemProvider;

	/**
	 * This creates an adapter for a {@link org.sopeco.model.configuration.measurements.TimeOut}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimeOutAdapter() {
		if (timeOutItemProvider == null) {
			timeOutItemProvider = new TimeOutItemProvider(this);
		}

		return timeOutItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.sopeco.model.configuration.measurements.ConstantValueAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstantValueAssignmentItemProvider constantValueAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link org.sopeco.model.configuration.measurements.ConstantValueAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstantValueAssignmentAdapter() {
		if (constantValueAssignmentItemProvider == null) {
			constantValueAssignmentItemProvider = new ConstantValueAssignmentItemProvider(this);
		}

		return constantValueAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.sopeco.model.configuration.measurements.DynamicValueAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DynamicValueAssignmentItemProvider dynamicValueAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link org.sopeco.model.configuration.measurements.DynamicValueAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDynamicValueAssignmentAdapter() {
		if (dynamicValueAssignmentItemProvider == null) {
			dynamicValueAssignmentItemProvider = new DynamicValueAssignmentItemProvider(this);
		}

		return dynamicValueAssignmentItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (measurementSpecificationItemProvider != null) measurementSpecificationItemProvider.dispose();
		if (experimentSeriesDefinitionItemProvider != null) experimentSeriesDefinitionItemProvider.dispose();
		if (explorationStrategyItemProvider != null) explorationStrategyItemProvider.dispose();
		if (configurationNodeItemProvider != null) configurationNodeItemProvider.dispose();
		if (numberOfRepetitionsItemProvider != null) numberOfRepetitionsItemProvider.dispose();
		if (timeOutItemProvider != null) timeOutItemProvider.dispose();
		if (constantValueAssignmentItemProvider != null) constantValueAssignmentItemProvider.dispose();
		if (dynamicValueAssignmentItemProvider != null) dynamicValueAssignmentItemProvider.dispose();
	}

}
